/**
 * Built-in en-gb substitution rules (US → British English).
 *
 * Extracted from tools.ts for readability. Seeded into
 * .bindery/translations.json by init_workspace when a language declares the
 * `en-gb` dialect but the translations file has no rules yet.
 */

export interface TranslationRule { from: string; to: string }

export const BUILTIN_EN_GB_RULES: TranslationRule[] = [
    { from: 'analyze',        to: 'analyse' },
    { from: 'analyzes',       to: 'analyses' },
    { from: 'analyzed',       to: 'analysed' },
    { from: 'analyzing',      to: 'analysing' },
    { from: 'canceled',       to: 'cancelled' },
    { from: 'canceling',      to: 'cancelling' },
    { from: 'center',         to: 'centre' },
    { from: 'centers',        to: 'centres' },
    { from: 'centered',       to: 'centred' },
    { from: 'centering',      to: 'centring' },
    { from: 'color',          to: 'colour' },
    { from: 'colors',         to: 'colours' },
    { from: 'colored',        to: 'coloured' },
    { from: 'coloring',       to: 'colouring' },
    { from: 'defense',        to: 'defence' },
    { from: 'destabilize',    to: 'destabilise' },
    { from: 'destabilizes',   to: 'destabilises' },
    { from: 'destabilized',   to: 'destabilised' },
    { from: 'destabilizing',  to: 'destabilising' },
    { from: 'equalize',       to: 'equalise' },
    { from: 'equalizes',      to: 'equalises' },
    { from: 'equalized',      to: 'equalised' },
    { from: 'equalizing',     to: 'equalising' },
    { from: 'favor',          to: 'favour' },
    { from: 'favors',         to: 'favours' },
    { from: 'favored',        to: 'favoured' },
    { from: 'favoring',       to: 'favouring' },
    { from: 'favorite',       to: 'favourite' },
    { from: 'favorites',      to: 'favourites' },
    { from: 'fiber',          to: 'fibre' },
    { from: 'gray',           to: 'grey' },
    { from: 'initialize',     to: 'initialise' },
    { from: 'initializes',    to: 'initialises' },
    { from: 'initialized',    to: 'initialised' },
    { from: 'initializing',   to: 'initialising' },
    { from: 'mesmerize',      to: 'mesmerise' },
    { from: 'mesmerizes',     to: 'mesmerises' },
    { from: 'mesmerized',     to: 'mesmerised' },
    { from: 'mesmerizing',    to: 'mesmerising' },
    { from: 'mom',            to: 'mum' },
    { from: 'offense',        to: 'offence' },
    { from: 'organize',       to: 'organise' },
    { from: 'organizes',      to: 'organises' },
    { from: 'organized',      to: 'organised' },
    { from: 'organizing',     to: 'organising' },
    { from: 'organization',   to: 'organisation' },
    { from: 'realize',        to: 'realise' },
    { from: 'realizes',       to: 'realises' },
    { from: 'realized',       to: 'realised' },
    { from: 'realizing',      to: 'realising' },
    { from: 'realization',    to: 'realisation' },
    { from: 'recognize',      to: 'recognise' },
    { from: 'recognizes',     to: 'recognises' },
    { from: 'recognized',     to: 'recognised' },
    { from: 'recognizing',    to: 'recognising' },
    { from: 'specialize',     to: 'specialise' },
    { from: 'specializes',    to: 'specialises' },
    { from: 'specialized',    to: 'specialised' },
    { from: 'specializing',   to: 'specialising' },
    { from: 'theater',        to: 'theatre' },
    { from: 'theaters',       to: 'theatres' },
    { from: 'traveler',       to: 'traveller' },
    { from: 'travelers',      to: 'travellers' },
    { from: 'traveled',       to: 'travelled' },
    { from: 'traveling',      to: 'travelling' },
];
