import type { TemplateContext, TemplateMeta } from './context';

export const meta: TemplateMeta = {
    file:    '.bindery/README.md',
    version: 9,
    label:   'bindery capabilities',
    zip:     null,
};

export function render(ctx: TemplateContext): string {
    const { title, storyFolder, notesFolder, arcFolder, charactersFolder, sessionFile, preferencesFile, arcGranularity, memoriesFolder } = ctx;
    return `# Bindery — capabilities for this workspace

This file is **the single source agents should consult to answer "What can Bindery do?"**
It is generated by Bindery itself (\`bindery init\` and \`setup_ai_files\`). Edits will be
overwritten on the next setup.

For richer narrative docs (install, contributing, release notes), see the project on
GitHub: <https://github.com/evdboom/Bindery> (README at
<https://github.com/evdboom/Bindery/blob/main/README.md>). Agents with internet access
may fetch it for context; otherwise, treat this file as the complete answer.

> Workspace: **${title}**

## What Bindery is

Bindery is a markdown book authoring toolkit with three surfaces:

1. **VS Code / Obsidian extension** — commands, format-on-save, export to DOCX/EPUB/PDF.
2. **MCP server** — programmatic tools for AI assistants (Claude, Copilot, Codex, Cursor).
3. **Skill workflows** — opinionated slash-commands like \`/review\`, \`/translate\`, \`/memory\`.

All three operate on the same workspace state: \`.bindery/settings.json\`,
\`.bindery/translations.json\`, the story folder, \`${notesFolder}/\`, \`${arcFolder}/\`, and
\`${memoriesFolder}/\`.

## Opinionated Authoring Layout

Bindery's default scaffold is intentionally structured so agents and authors can
work from the same map:

| Path | Purpose |
|---|---|
| \`${sessionFile}\` | Ephemeral working state: current focus, next actions, open questions, handoff notes. Maintained via \`session_focus_*\` tools and host commands. |
| \`${preferencesFile}\` | Durable working preferences — "do it like this for me". User-owned: Bindery scaffolds it once and never edits it. |
| \`${arcFolder}/index.md\` | Arc map and links to structure files. |
| \`${arcFolder}/Overall.md\` | Whole-book arc, promise, turns, ending direction, and open questions. |
| \`${arcFolder}/Acts/\` | Act-level arc files. Default arc granularity: \`${arcGranularity}\`. |
| \`${charactersFolder}/index.md\` | Cast overview. |
| \`${charactersFolder}/<character>.md\` | One durable profile per character. |
| \`${notesFolder}/Inbox.md\` | Loose notes, pasted mobile chats, and unsorted ideas before triage. Triage with \`inbox_process\` / \`inbox_resolve\`. |
| \`${notesFolder}/World/\`, \`${notesFolder}/Scenes/\`, \`${notesFolder}/Research/\` | Structured supporting notes. |
| \`${memoriesFolder}/global.md\` | Durable cross-session decisions and story rules. |
| \`${storyFolder}/\` | Chapter source files by language. |

Treat \`${arcFolder}/\` as story architecture, \`${charactersFolder}/\` as cast truth,
\`${notesFolder}/\` as supporting reference, and \`${memoriesFolder}/\` as session memory.

## VS Code / Obsidian commands (Command Palette → "Bindery: …")

| Command | What it does |
|---|---|
| \`Bindery: Initialize Workspace\` | Create \`.bindery/settings.json\`, \`.bindery/translations.json\`, this README, and the opinionated Arc / Notes / Characters / SESSION / PREFERENCES / memory / status scaffold. |
| \`Bindery: Setup AI Assistant Files\` | Generate CLAUDE.md / copilot-instructions.md / cursor rules / AGENTS.md and refresh this capabilities doc. |
| \`Bindery: Format Typography\` / \`Format All Markdown in Folder\` | Curly quotes, em-dashes, ellipses, etc. |
| \`Bindery: Merge Chapters → Markdown / DOCX / EPUB / PDF / All Formats\` | Build a deliverable from chapter files. |
| \`Bindery: Find Probable US→UK Words\` | Surface probable US spellings in EN source. |
| \`Bindery: Add Dialect Rule\` / \`Add Translation (Glossary)\` / \`Add Language\` | Maintain dialect substitutions, glossary entries, and language scaffolding. |
| \`Bindery: Open translations.json\` | Open the per-language rules file. |
| \`Bindery: Insert Review Start Marker (or wrap selection)\` | Insert \`<!-- Bindery: Review start -->\`, or wrap the current selection in matched start/stop markers. |
| \`Bindery: Insert Review Stop Marker\` | Insert \`<!-- Bindery: Review stop -->\` at the cursor. |
| \`Bindery: List/Create/Append Notes\` | Work with story notes under \`${notesFolder}/\` through the same structured tools agents use. |
| \`Bindery: List/Create/Update Character Profile\` | Maintain structured character files under \`${charactersFolder}/\`. |
| \`Bindery: List/Create/Update Arc File\` | Maintain story architecture files under \`${arcFolder}/\`. |
| \`Bindery: List/Append/Compact Memories\` | Maintain durable session-memory files under \`${memoriesFolder}/\`. |
| \`Bindery: Show/Update Chapter Status\` | Read or update \`.bindery/chapter-status.json\`. |
| \`Bindery: Show/Update Session Focus\` / \`Append Handoff Note\` | Read or update the neutral working-state sections of \`${sessionFile}\`. |
| \`Bindery: Process Inbox\` / \`Resolve Inbox Items\` | Triage \`${notesFolder}/Inbox.md\`: list items with stable numbers, then remove routed items by number. |
| \`Bindery: Register MCP Server\` | Write \`.vscode/mcp.json\` so Claude / Codex pick the bundled server up. |

### Default keybindings (markdown editors only)

| Shortcut | Command |
|---|---|
| \`Ctrl+K Ctrl+B\` | Format Typography |
| \`Ctrl+K Ctrl+,\` | Insert Review Start Marker (or wrap selection) |
| \`Ctrl+K Ctrl+.\` | Insert Review Stop Marker |

These only fire while a markdown file is focused (\`editorTextFocus && resourceLangId == markdown\`). Rebind in **File → Preferences → Keyboard Shortcuts** if they collide with another extension. On macOS, swap \`Ctrl\` for \`Cmd\`.

## MCP tools

Use these from any MCP-aware assistant. Tools tagged **(reads)** are safe; tools
tagged **(writes)** modify files or git state.

| Tool | What it does |
|---|---|
| \`health\` (reads) | Workspace status: settings, index, AI-file versions, embedding backend. |
| \`identify_book\` (reads) | Confirm the active book root and registry entry. |
| \`init_workspace\` (writes) | Create \`.bindery/settings.json\`, \`.bindery/translations.json\`, generated \`.bindery/README.md\`, and the opinionated Arc / Notes / Characters / SESSION / PREFERENCES / memory / status scaffold. |
| \`update_workspace\` (writes) | \`git fetch\` + pull, optional branch switch, optional auto-stash. |
| \`settings_update\` (writes) | Patch \`.bindery/settings.json\` from an agent. |
| \`setup_ai_files\` (writes) | (Re)generate AI instruction files + refresh this capabilities doc. |
| \`get_text\` / \`get_chapter\` / \`get_book_until\` / \`get_overview\` / \`get_notes\` (reads) | Read source files, chapters, ranges, and notes. |
| \`note_list\` / \`note_get\` / \`note_create\` / \`note_append\` (reads / writes) | First-class story note management under \`${notesFolder}/\`. |
| \`character_list\` / \`character_get\` / \`character_create\` / \`character_update\` (reads / writes) | Structured character profiles under \`${charactersFolder}/\`. |
| \`arc_list\` / \`arc_get\` / \`arc_create\` / \`arc_update\` (reads / writes) | Structured story-architecture files under \`${arcFolder}/\`. |
| \`search\` (reads) | BM25 / semantic search across the corpus (Ollama optional). |
| \`index_build\` / \`index_status\` (writes / reads) | Build or inspect the lexical/semantic index. |
| \`format\` (writes) | Apply typography to a file or folder (\`dryRun\` supported). |
| \`get_review_text\` (writes) | Returns the **git diff of uncommitted changes** *plus* any regions wrapped in \`<!-- Bindery: Review start --> ... <!-- Bindery: Review stop -->\` markers. Marker regions surface even after a commit, so committed work-in-progress can still be reviewed. \`autoStage: true\` stages files **and** consumes (removes) the marker lines. |
| \`git_snapshot\` (writes) | Commit changes in bindery workspace, optional push. |
| \`get_translation\` / \`add_translation\` (reads / writes) | Glossary lookup and upsert per target language. |
| \`get_dialect\` / \`add_dialect\` (reads / writes) | Dialect substitution lookup and upsert (e.g. \`en-gb\`). |
| \`add_language\` (writes) | Scaffold a new language under the story folder. |
| \`memory_list\` / \`memory_append\` / \`memory_compact\` (reads / writes) | Manage \`.bindery/memories/\` files. |
| \`chapter_status_get\` / \`chapter_status_update\` (reads / writes) | Per-chapter progress tracker in \`.bindery/chapter-status.json\`. |
| \`session_focus_get\` / \`session_focus_update\` (reads / writes) | Read or update the neutral working-state sections of \`${sessionFile}\` (Current Focus, Next Actions, Open Questions, Handoff Notes). Leaves \`${preferencesFile}\` and other content untouched. |
| \`inbox_process\` / \`inbox_resolve\` (reads / writes) | \`inbox_process\` enumerates \`${notesFolder}/Inbox.md\` items with stable numbers and proposes destinations (read-only); \`inbox_resolve\` removes already-routed items by number after confirmation. |

### Tool Workflow Shortcuts

- Use \`init_workspace\` first for a new book. It creates the settings, translation file, generated capability README, and the default authoring scaffold.
- Use \`setup_ai_files\` after init or when \`health\` reports outdated AI files. It refreshes CLAUDE.md, Copilot instructions, Cursor rules, AGENTS.md, Claude skills, skill zips, and this capability README.
- Use \`arc_*\` for story architecture under \`${arcFolder}/\`.
- Use \`character_*\` for cast profiles under \`${charactersFolder}/\`.
- Use \`note_*\` for canonical story notes under \`${notesFolder}/\`.
- Use \`get_notes\` for broad note lookup, \`memory_*\` for durable session decisions, \`chapter_status_*\` for progress state, and \`session_focus_*\` for ephemeral current-focus/handoff in \`${sessionFile}\`.
- Send rough, unsorted, or pasted material to \`${notesFolder}/Inbox.md\` (e.g. \`note_append\`), then triage it with \`inbox_process\` (propose) and \`inbox_resolve\` (clear routed items) — do not dump it into memory.

### Current Tool Boundaries

- Dedicated note, character, arc, memory, chapter-status, session-focus, and inbox-triage tools are available now.
- \`inbox_process\` only reads and proposes; \`inbox_resolve\` only removes items you name after they have been routed. Neither moves or categorizes content on its own — route confirmed items with the destination tools first.
- \`session_focus_*\` updates only the neutral working-state sections of \`${sessionFile}\`. \`${preferencesFile}\` is durable and user-owned — Bindery scaffolds it once and never edits it; propose preference changes for the author to apply.
- VS Code and Obsidian host commands now mirror the structured note, character, arc, memory, chapter-status, and session-focus tools. Host prompts cover common fields; agents can still call the MCP tools directly for complete structured payloads.

## Review markers

Bindery review markers let an author tag arbitrary regions for the next review
pass — even after those edits have been committed. Use them when you commit
work-in-progress and continue on another machine.

\`\`\`
<!-- Bindery: Review start -->
...lines you want reviewed...
<!-- Bindery: Review stop -->
\`\`\`

- The stop marker is **optional** — an unclosed start runs to end of file.
- Multiple regions per file are supported.
- Insert markers via the VS Code / Obsidian commands above, or just type them.
- \`get_review_text(autoStage: true)\` returns marker regions in addition to the
  git diff and **removes** the marker lines as part of staging, so the next
  review pass starts clean.

## Skill workflows (Claude / Copilot Chat / etc.)

Generated under \`.claude/skills/<name>/SKILL.md\`. Trigger them with a slash
command or by paraphrasing the description.

| Skill | Trigger phrases |
|---|---|
| \`/review\` | "review chapter X", "review my changes", "quick review" |
| \`/translation-review\` | "review my translation", "what do you think" (translation focus) |
| \`/translate\` | "translate chapter X", "spot-check the NL of chapter X" |
| \`/brainstorm\` | "I'm stuck", "help me think of ideas" |
| \`/plan-beats\` | "help me plan the beats", "refine chapter beats" |
| \`/character-setup\` | "make a character profile", "help me define this character" |
| \`/memory\` | "save what we decided", end-of-session memory updates |
| \`/status\` | "where are we", "what's the book status" |
| \`/continuity\` | "check chapter X for errors", "continuity check" |
| \`/read-aloud\` | "read this aloud", reading-aloud test |
| \`/read-in\` | start-of-session context loading |
| \`/proof-read\` | "proofread chapter X", "get reader feedback" |

## How to answer "What can Bindery do?"

When an agent is asked what Bindery can do for this project, it should:

1. Read **this file** (\`.bindery/README.md\`) — it is intentionally complete.
2. Cross-check live state with \`health\` if the user asks about the index,
   AI-file freshness, or the embedding backend.
3. For narrative / install / contribution guidance, point the user to
   <https://github.com/evdboom/Bindery> (or fetch the README from
   <https://github.com/evdboom/Bindery/blob/main/README.md> if internet access
   is available) — not for capability listings.
`;
}
