/**
 * Bindery — AI assistant setup
 *
 * Generates AI assistant instruction files and Claude skill templates from
 * the project's .bindery/settings.json. Each target produces different files:
 *
 *   claude    → CLAUDE.md + .claude/skills/<skill>/SKILL.md
 *   copilot   → .github/copilot-instructions.md
 *   cursor    → .cursor/rules
 *   agents    → AGENTS.md  (OpenAI Agents, Aider, Codex, etc.)
 *
 * Templates live in ai-setup-templates.ts, which is a copy of
 * mcp-ts/src/templates.ts — the single source of truth.
 * The copy is kept in sync by the CI workflow and locally via:
 *   cp mcp-ts/src/templates.ts vscode-ext/src/ai-setup-templates.ts
 */

import * as fs   from 'node:fs';
import * as path from 'node:path';
import type { WorkspaceSettings } from './workspace';
import type { LanguageConfig }    from './merge';

// ─── Resilient template loader ────────────────────────────────────────────────
// ai-setup-templates.ts is a copy of mcp-ts/src/templates.ts generated by CI.
// In local dev and test runs the copy may be absent. We try the copy first and
// fall back to the source file so tests and local builds don't hard-fail with an
// opaque module-not-found error.

// Forward-reference is fine in TypeScript — TemplateContext is defined below.
// eslint-disable-next-line @typescript-eslint/no-use-before-define
type RenderTemplateFn = (name: string, ctx: TemplateContext) => string;

function loadRenderTemplate(): RenderTemplateFn {
    // 1. Preferred: the in-tree copy (always present after CI sync / vsce publish)
    try {
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const mod = require('./ai-setup-templates') as { renderTemplate: RenderTemplateFn };
        return mod.renderTemplate;
    } catch {
        // copy not present — fall through to fallback
    }

    // 2. Fallback: load from the MCP source — only useful inside the mono-repo
    //    (e.g. `vscode-ext npm test` when ai-setup-templates.ts hasn't been synced yet).
    //    __dirname is `vscode-ext/out/` in compiled output and `vscode-ext/src/` in ts-node/vitest,
    //    so two levels up always lands at the repo root where mcp-ts/ lives.
    //    This path will NOT exist inside a published .vsix (that's fine — the copy is always
    //    present there after the CI sync step).
    const fallbackPath = path.resolve(__dirname, '..', '..', 'mcp-ts', 'src', 'templates');
    try {
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const mod = require(fallbackPath) as { renderTemplate: RenderTemplateFn };
        return mod.renderTemplate;
    } catch {
        // source also missing — give a clear, actionable error
    }

    throw new Error(
        'Bindery: template file not found.\n' +
        'Run the sync step to generate vscode-ext/src/ai-setup-templates.ts:\n' +
        '  cp mcp-ts/src/templates.ts vscode-ext/src/ai-setup-templates.ts\n' +
        'Or build the MCP server first:\n' +
        '  cd mcp-ts && npm run compile',
    );
}

const renderTemplate = loadRenderTemplate();

// ─── Public types ─────────────────────────────────────────────────────────────

export type AiTarget = 'claude' | 'copilot' | 'cursor' | 'agents';

export interface AiSetupOptions {
    root:        string;
    settings:    WorkspaceSettings;
    targets:     AiTarget[];
    /** Skills to generate for the claude target. */
    skills?:     SkillTemplate[];
    /** Overwrite existing files? Default false (skip existing). */
    overwrite?:  boolean;
}

export interface AiSetupResult {
    created:  string[];   // files created
    skipped:  string[];   // files that existed and were not overwritten
}

export type SkillTemplate =
    | 'review'
    | 'brainstorm'
    | 'memory'
    | 'translate'
    | 'status'
    | 'continuity'
    | 'read-aloud'
    | 'read-in';

export const ALL_SKILLS: SkillTemplate[] = [
    'review', 'brainstorm', 'memory', 'translate', 'status', 'continuity', 'read-aloud', 'read-in',
];

// ─── Entry point ──────────────────────────────────────────────────────────────

export function setupAiFiles(options: AiSetupOptions): AiSetupResult {
    const { root, settings, targets, skills = ALL_SKILLS, overwrite = false } = options;
    const result: AiSetupResult = { created: [], skipped: [] };

    const ctx = buildContext(settings);

    for (const target of targets) {
        switch (target) {
            case 'claude':
                writeFile(root, 'CLAUDE.md', renderTemplate('claude', ctx), overwrite, result);
                for (const skill of skills) {
                    const skillDir = path.join('.claude', 'skills', skill);
                    writeFile(root, path.join(skillDir, 'SKILL.md'), renderTemplate(skill, ctx), overwrite, result);
                }
                break;

            case 'copilot':
                writeFile(root, path.join('.github', 'copilot-instructions.md'), renderTemplate('copilot', ctx), overwrite, result);
                break;

            case 'cursor':
                writeFile(root, path.join('.cursor', 'rules'), renderTemplate('cursor', ctx), overwrite, result);
                break;

            case 'agents':
                writeFile(root, 'AGENTS.md', renderTemplate('agents', ctx), overwrite, result);
                break;
        }
    }

    return result;
}

interface TemplateContext {
    title:          string;
    author:         string;
    description:    string;
    genre:          string;
    audience:       string;
    storyFolder:    string;
    notesFolder:    string;
    arcFolder:      string;
    memoriesFolder: string;
    languages:      LanguageConfig[];
    langList:       string;
    hasMultiLang:   boolean;
}

function buildContext(s: WorkspaceSettings): TemplateContext {
    const title       = (typeof s.bookTitle === 'string' ? s.bookTitle : undefined) ?? 'Untitled';
    const author      = s.author      ?? '';
    const description = s.description ?? '';
    const genre       = s.genre       ?? '';
    const audience    = s.targetAudience ?? '';
    const storyFolder = s.storyFolder  ?? 'Story';
    const notesFolder = 'Notes';
    const arcFolder   = 'Arc';
    const languages   = s.languages   ?? [];

    const langList = languages.length > 0
        ? languages.map((l, i) => i === 0 ? `${l.code} (source)` : `${l.code} (translation)`).join(', ')
        : 'EN (source)';

    return { title, author, description, genre, audience, storyFolder, notesFolder, arcFolder, languages, langList, hasMultiLang: languages.length > 1, memoriesFolder: '.bindery/memories' };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function writeFile(
    root:      string,
    relPath:   string,
    content:   string,
    overwrite: boolean,
    result:    AiSetupResult
): void {
    const full = path.join(root, relPath);
    if (fs.existsSync(full) && !overwrite) {
        result.skipped.push(relPath);
        return;
    }
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
    result.created.push(relPath);
}

