import type { TemplateContext, TemplateMeta } from './context';

export const meta: TemplateMeta = {
    file:    '.bindery/README.md',
    version: 2,
    label:   'bindery capabilities',
    zip:     null,
};

export function render(ctx: TemplateContext): string {
    const { title } = ctx;
    return `# Bindery — capabilities for this workspace

This file is **the single source agents should consult to answer "What can Bindery do?"**
It is generated by Bindery itself (\`bindery init\` and \`setup_ai_files\`). Edits will be
overwritten on the next setup. Open the root \`README.md\` for richer narrative docs.

> Workspace: **${title}**

## What Bindery is

Bindery is a markdown book authoring toolkit with three surfaces:

1. **VS Code extension** — commands, format-on-save, export to DOCX/EPUB/PDF.
2. **MCP server** — programmatic tools for AI assistants (Claude, Copilot, Codex, Cursor).
3. **Skill workflows** — opinionated slash-commands like \`/review\`, \`/translate\`, \`/memory\`.

All three operate on the same workspace state: \`.bindery/settings.json\`,
\`.bindery/translations.json\`, the story folder, \`Notes/\`, \`Arc/\`, and
\`.bindery/memories/\`.

## VS Code commands (Command Palette → "Bindery: …")

| Command | What it does |
|---|---|
| \`Bindery: Initialize Workspace\` | Create \`.bindery/settings.json\`, \`.bindery/translations.json\`, and this README. |
| \`Bindery: Setup AI Assistant Files\` | Generate CLAUDE.md / copilot-instructions.md / cursor rules / AGENTS.md and refresh this capabilities doc. |
| \`Bindery: Format Typography\` / \`Format All Markdown in Folder\` | Curly quotes, em-dashes, ellipses, etc. |
| \`Bindery: Merge Chapters → Markdown / DOCX / EPUB / PDF / All Formats\` | Build a deliverable from chapter files. |
| \`Bindery: Find Probable US→UK Words\` | Surface probable US spellings in EN source. |
| \`Bindery: Add Dialect Rule\` / \`Add Translation (Glossary)\` / \`Add Language\` | Maintain dialect substitutions, glossary entries, and language scaffolding. |
| \`Bindery: Open translations.json\` | Open the per-language rules file. |
| \`Bindery: Insert Review Start Marker (or wrap selection)\` | Insert \`<!-- Bindery: Review start -->\`, or wrap the current selection in matched start/stop markers. |
| \`Bindery: Insert Review Stop Marker\` | Insert \`<!-- Bindery: Review stop -->\` at the cursor. |
| \`Bindery: Register MCP Server\` | Write \`.vscode/mcp.json\` so Claude / Codex pick the bundled server up. |

### Default keybindings (markdown editors only)

| Shortcut | Command |
|---|---|
| \`Ctrl+K Ctrl+B\` | Format Typography |
| \`Ctrl+K Ctrl+,\` | Insert Review Start Marker (or wrap selection) |
| \`Ctrl+K Ctrl+.\` | Insert Review Stop Marker |

These only fire while a markdown file is focused (\`editorTextFocus && resourceLangId == markdown\`). Rebind in **File → Preferences → Keyboard Shortcuts** if they collide with another extension. On macOS, swap \`Ctrl\` for \`Cmd\`.

## MCP tools

Use these from any MCP-aware assistant. Tools tagged **(reads)** are safe; tools
tagged **(writes)** modify files or git state.

| Tool | What it does |
|---|---|
| \`health\` (reads) | Workspace status: settings, index, AI-file versions, embedding backend. |
| \`identify_book\` (reads) | Confirm the active book root and registry entry. |
| \`init_workspace\` (writes) | Create \`.bindery/settings.json\` with title/author/story-folder defaults. |
| \`update_workspace\` (writes) | \`git fetch\` + pull, optional branch switch, optional auto-stash. |
| \`settings_update\` (writes) | Patch \`.bindery/settings.json\` from an agent. |
| \`setup_ai_files\` (writes) | (Re)generate AI instruction files + refresh this capabilities doc. |
| \`get_text\` / \`get_chapter\` / \`get_book_until\` / \`get_overview\` / \`get_notes\` (reads) | Read source files, chapters, ranges, and notes. |
| \`search\` (reads) | BM25 / semantic search across the corpus (Ollama optional). |
| \`index_build\` / \`index_status\` (writes / reads) | Build or inspect the lexical/semantic index. |
| \`format\` (writes) | Apply typography to a file or folder (\`dryRun\` supported). |
| \`get_review_text\` (writes) | Returns the **git diff of uncommitted changes** *plus* any regions wrapped in \`<!-- Bindery: Review start --> ... <!-- Bindery: Review stop -->\` markers. Marker regions surface even after a commit, so committed work-in-progress can still be reviewed. \`autoStage: true\` stages files **and** consumes (removes) the marker lines. |
| \`git_snapshot\` (writes) | Commit changes in story / notes / arc folders, optional push. |
| \`get_translation\` / \`add_translation\` (reads / writes) | Glossary lookup and upsert per target language. |
| \`get_dialect\` / \`add_dialect\` (reads / writes) | Dialect substitution lookup and upsert (e.g. \`en-gb\`). |
| \`add_language\` (writes) | Scaffold a new language under the story folder. |
| \`memory_list\` / \`memory_append\` / \`memory_compact\` (reads / writes) | Manage \`.bindery/memories/\` files. |
| \`chapter_status_get\` / \`chapter_status_update\` (reads / writes) | Per-chapter progress tracker in \`.bindery/chapter-status.json\`. |
| \`git_snapshot\` (writes) | Save a snapshot of content folders. |

## Review markers

Bindery review markers let an author tag arbitrary regions for the next review
pass — even after those edits have been committed. Use them when you commit
work-in-progress and continue on another machine.

\`\`\`
<!-- Bindery: Review start -->
...lines you want reviewed...
<!-- Bindery: Review stop -->
\`\`\`

- The stop marker is **optional** — an unclosed start runs to end of file.
- Multiple regions per file are supported.
- Insert markers via the VS Code commands above, or just type them.
- \`get_review_text(autoStage: true)\` returns marker regions in addition to the
  git diff and **removes** the marker lines as part of staging, so the next
  review pass starts clean.

## Skill workflows (Claude / Copilot Chat / etc.)

Generated under \`.claude/skills/<name>/SKILL.md\`. Trigger them with a slash
command or by paraphrasing the description.

| Skill | Trigger phrases |
|---|---|
| \`/review\` | "review chapter X", "review my changes", "quick review" |
| \`/translation-review\` | "review my translation", "what do you think" (translation focus) |
| \`/translate\` | "translate chapter X", "spot-check the NL of chapter X" |
| \`/brainstorm\` | "I'm stuck", "help me think of ideas" |
| \`/memory\` | "save what we decided", end-of-session memory updates |
| \`/status\` | "where are we", "what's the book status" |
| \`/continuity\` | "check chapter X for errors", "continuity check" |
| \`/read-aloud\` | "read this aloud", reading-aloud test |
| \`/read-in\` | start-of-session context loading |
| \`/proof-read\` | "proofread chapter X", "get reader feedback" |

## How to answer "What can Bindery do?"

When an agent is asked what Bindery can do for this project, it should:

1. Read **this file** (\`.bindery/README.md\`) — it is intentionally complete.
2. Cross-check live state with \`health\` if the user asks about the index,
   AI-file freshness, or the embedding backend.
3. Defer to the root \`README.md\` only for narrative / install / contribution
   guidance — not for capability listings.
`;
}
