import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/chapter-image/SKILL.md',
    version: 1,
    label:   'chapter-image skill',
};

const CONTENT = [
    '---',
    'name: chapter-image',
    'description: Bindery workspace - Create a non-spoiling, style-consistent illustration for a chapter using the book\'s image style guide and previously generated images as reference. Use for /chapter-image, "make a chapter cover", "create a chapter image", or "generate an illustration for chapter X".',
    "argument-hint: 'chapter number (optional)'",
    '---',
    '# Skill: /chapter-image',
    '',
    'Create one illustration that gives a reader an inviting, spoiler-safe sense of a chapter before they begin reading, staying visually consistent with the book\'s style guide and any images already generated.',
    '',
    '## Prerequisites',
    '1. A Bindery workspace. If unsure, call `bindery_identify_book` to check. If no workspace is found, tell the user and stop.',
    '2. An existing image style guide. `CHAPTER_IMAGE_STYLE.md` (book root) read with `bindery_get_text`. If none is found, tell the user and offer to run `/image-style` first, then stop — do not improvise a style guide or generate an image without one.',
    '3. Image generation capability in your environment. If none is available, tell the user and either follow this skill and provide a prompt for them to run in their own image-generation tool, or stop.',
    '',
    '## Trigger',
    'User says `/chapter-image`, "make a chapter cover", "create a chapter image", "generate an illustration for chapter X", or "add a cover image to this chapter".',
    '',
    'If no image style guide exists, tell the user none was found and that consistent chapter images depend on one. Offer to run `/image-style` first, then stop — do not improvise a style guide or generate an image without one.',
    '',
    '## Tools',
    '- `bindery_get_text(path)` — read the style guide and `.bindery/settings.json`',
    '- `bindery_get_chapter(chapterNumber, language)` — read the full chapter text',
    '- `bindery_character_get(name)` / `bindery_get_notes(category, name)` — pull visual/continuity facts for characters, creatures, or locations appearing in the scene',
    '- `bindery_search(query, language)` — check how a scene or detail was described elsewhere if the chapter text is ambiguous',
    '- Your environment\'s file-browsing capability — list `images/` for previously generated art',
    '- Your environment\'s image-viewing capability — inspect existing images for visual continuity before drafting a new prompt',
    '- Your environment\'s image-generation capability — produce the illustration',
    '',
    '## Steps',
    '',
    '### 1. Load the style guide and chapter',
    '- Read the style guide found above. Treat its style block as required content for every prompt; include a reference block only when the scene actually contains that character, creature, vehicle, or location.',
    '- Identify the target chapter and language (ask if unclear; default to the book\'s source language). Read it in full with `bindery_get_chapter`.',
    '- For continuity-sensitive scenes, load the relevant character profile or notes before forming the prompt. Do not assume details from the chapter title alone.',
    '',
    '### 2. Check existing artwork',
    'List the `images/` folder (or the folder named in the style guide, if different) and view any existing chapter or cover images. The new image must feel continuous with them in style, palette, and character treatment — without copying their exact composition.',
    '',
    '### 3. Choose the scene',
    'Select one early or atmospheric visual hook that represents the chapter\'s mood, setting, journey, or immediate problem — a moment a reader could encounter in the opening third.',
    '',
    'Avoid depicting or strongly signalling later reveals, betrayals, identities, outcomes, villains, injuries, or solutions. Keep threats indirect when their exact nature is a reveal. Do not put a title, words, lettering, logo, or watermark in the artwork — even if the style guide does not repeat that rule.',
    '',
    'Use a readable, still composition rather than a literal collage of chapter events. The scene does not need to include every important character; a landscape or object-focused image can work when it fits the chapter better.',
    '',    
    '### 4. Generate and assess',
    'Use your environment\'s image-generation capability. Build a concise production prompt from:',
    '- The style guide\'s style block (always)',
    '- Any relevant reference blocks (only if that element appears in the scene)',
    '- A spoiler-safe scene description for the chosen moment',
    '- Composition, lighting, and mood appropriate to the scene',
    '- The style guide\'s default size/orientation for chapter images (fall back to a portrait orientation if none is specified)',
    '- An explicit no-text/no-logo/no-watermark constraint',
    '',
    'Inspect the result before accepting it. It must have a clear focal point, coherent anatomy/proportions, and match the established style. If it misses an essential constraint, make one targeted revision; do not endlessly iterate.',
    '',
    '### 5. Save and link',
    'Save the selected image into the `images/` folder using the project\'s existing chapter-image naming convention if one is visible (e.g. `chapter<N>.jpg`); otherwise use `images/chapter<N>.jpg` with the chapter number and no leading zeroes. Do not overwrite an existing chapter image unless the user explicitly asks for a replacement.',
    '',
    'Add the image immediately beneath the H1 in the matching chapter, in every language, using standard markdown image syntax with a path relative to the chapter file:',
    '',
    '```markdown',
    '![](relative/path/to/images/chapter<N>.jpg)',
    '```',
    '',
    'Compute the relative path from each chapter file\'s actual folder depth — do not assume a fixed depth across projects. Do not alter chapter prose.',
    '',
    '### 6. Report back',
    'Report the saved image path, the chapter(s) updated, the final prompt used, and any non-obvious spoiler-avoidance choice.',
    '',
    '## Rules',
    '- Never generate a chapter image without an existing style guide — redirect to `/image-style` instead.',
    '- Never add a title, lettering, logo, or watermark to a chapter illustration.',
    '- Never depict a scene that spoils a later reveal.',
    '- This skill is for chapter illustrations, not the book cover. Cover art is book-level metadata configured via the `coverImage` setting — point the user there if they ask for a cover image instead.',
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
