import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/character-setup/SKILL.md',
    version: 3,
    label:   'character-setup skill',
};

const CONTENT = [
    '---',
    'name: character-setup',
    'description: Bindery workspace - Create or refine structured character profiles. Use for /character-setup, "help me define this character", "make a character profile", "update this character", or "describe the cast".',
    "argument-hint: 'character name or cast group (optional)'",
    '---',
    '# Skill: /character-setup',
    '',
    'Build or refine character profiles using Bindery structured character tools.',
    '',
    '## Prerequisites',
    'This skill requires a Bindery workspace. If unsure, call `bindery_identify_book` to check. If no workspace is found, tell the user and stop.',
    '',
    '## Trigger',
    'User says `/character-setup`, "help me define this character", "make a character profile", "update this character", "describe the cast", or asks for durable character setup/description.',
    '',
    '## Clarify first',
    '- Character name: ask if no target is clear.',
    '- Mode: create | update | review. Infer from context when possible.',
    '- Scope: full profile | quick profile | one section such as relationships, appearance, or narrative arc.',
    '',
    '## Tools',
    'Use these Bindery MCP tools:',
    '- `bindery_character_list(name?)` — inspect existing profiles before creating duplicates',
    '- `bindery_character_get(name)` — read an existing structured profile',
    '- `bindery_character_create(...)` — create a profile and update the character index',
    '- `bindery_character_update(...)` — update known profile fields and refresh the index row',
    '- `bindery_get_notes(category: "Characters")` — broad lookup for older note layouts or unstructured character notes',
    '- `bindery_search(query, language)` — find in-story mentions, first appearance, and continuity facts',
    '- `bindery_get_chapter(chapterNumber, language)` / `bindery_get_book_until(...)` — inspect source text when the profile must reflect written canon',
    '- `bindery_arc_list` / `bindery_arc_get` — check relevant arc movement before writing narrative-arc fields',
    '',
    '## Profile fields',
    'Bindery character profiles use these durable fields:',
    '- role',
    '- age',
    '- origin',
    '- skills',
    '- strengths',
    '- weaknesses',
    '- personality',
    '- background',
    '- narrativeArc',
    '- appearanceNotes',
    '- relationships',
    '- firstAppearance',
    '- openQuestions',
    '- continuityNotes',
    '- indexNotes',
    '',
    '## Steps',
    '',
    '### 1. Check for an existing profile',
    'Call `bindery_character_list` with the character name or likely spelling. If a plausible match exists, call `bindery_character_get` and update it instead of creating a duplicate.',
    '',
    '### 2. Gather canon and planning context',
    '- Use `bindery_search` for the character name and aliases.',
    '- Use `bindery_get_notes(category: "Characters")` if older character notes may exist.',
    '- Use `bindery_arc_list` / `bindery_arc_get` when narrative movement or act-level purpose matters.',
    '- Ask the user for missing intent before inventing durable facts.',
    '',
    '### 3. Draft the profile',
    'Separate confirmed canon from open questions. Put uncertainties in `openQuestions`, not in factual fields. Keep descriptions useful for continuity and future writing rather than decorative.',
    '',
    '### 4. Write the profile',
    '- For a new character, call `bindery_character_create` with the populated fields.',
    '- For an existing character, call `bindery_character_update` with only fields that should change.',
    '- Do not use generic file edits for character profiles when `bindery_character_create` or `bindery_character_update` can express the change.',
    '',
    '### 5. Report back',
    'Summarize what changed, list any open questions, and mention the profile path returned by the tool.',
    '',
    '## Rules',
    '- Do not overwrite confirmed canon without calling out the change.',
    '- Keep profiles concise enough to scan, but complete enough to support continuity checks.',
    '- Use `openQuestions` for speculation and unresolved author choices.',
    '- Use `continuityNotes` for facts that future chapters must not contradict.',
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
