import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/image-style/SKILL.md',
    version: 1,
    label:   'image-style skill',
};

const CONTENT = [
    '---',
    'name: image-style',
    'description: Bindery workspace - Interview the user to define a reusable illustration style guide for this book\'s cover and chapter images. Use for /image-style, "set up my image style", "define my book\'s art style", "create an image style guide", or when a chapter-image request has no style guide to work from.',
    '---',
    '# Skill: /image-style',
    '',
    'Build or refine `CHAPTER_IMAGE_STYLE.md` — a reusable style guide that keeps every generated cover and chapter image visually consistent, the way `PREFERENCES.md` keeps writing conventions consistent.',
    '',
    '## Prerequisites',
    'This skill requires a Bindery workspace. If unsure, call `bindery_identify_book` to check. If no workspace is found, tell the user and stop.',
    '',
    '## Trigger',
    'User says `/image-style`, "set up my image style", "define my book\'s art style", "create an image style guide", or the `/chapter-image` skill reports that no style guide exists yet.',
    '',
    '## Tools',
    '- `bindery_get_text(path)` — read `.bindery/settings.json`, an existing `CHAPTER_IMAGE_STYLE.md`, or legacy locations',
    '- Your environment\'s file-browsing capability — list the `images/` folder for existing cover or chapter art to use as a style baseline',
    '- Your environment\'s image-viewing capability — inspect existing images before describing the style in words',
    '- Your environment\'s generic file-write capability — there is no dedicated Bindery tool for this file, so create or update it directly',
    '',
    '## Steps',
    '',
    '### 1. Check for an existing guide',
    'Look for a style guide in this order, and read it with `bindery_get_text` if found:',
    '1. `CHAPTER_IMAGE_STYLE.md` (book root — preferred location)',
    '2. `images/image-style.md`',
    '3. `images/source/image-style.md`',
    '',
    'If one exists, summarize it back to the user and ask whether they want to refine it or start over, rather than silently overwriting it.',
    '',
    '### 2. Gather context',
    '- Read `.bindery/settings.json` with `bindery_get_text` for the book\'s title, genre, and target audience — these should inform style suggestions (a middle-grade adventure and a literary thriller want different art).',
    '- List the `images/` folder. If cover or chapter images already exist, view a couple of them. Treat their visible qualities as a strong baseline rather than starting from a blank slate — the point of this skill is continuity, not reinvention.',
    '',
    '### 3. Interview the user',
    'Ask concrete, easy-to-answer questions rather than one open-ended "describe your style" prompt. Offer short menus of options and let the user pick, mix, or describe their own:',
    '',
    '- **Art style family** — offer examples such as: painterly/semi-realistic illustration, flat vector or storybook illustration, watercolor, anime/manga, photoreal/cinematic, 3D-render, mixed-media collage, minimalist/silhouette.',
    '- **Mood and palette** — warm vs. cool, saturated vs. muted, high-contrast vs. soft, and any color(s) that should recur (e.g. a signature magic glow, a faction color).',
    '- **Level of stylization** — realistic proportions vs. stylized/exaggerated, and how much environmental detail vs. character focus.',
    '- **Character rendering rules** — should main characters be shown face-on, from behind, or in silhouette? Answer matters for consistency across many generated images without a fixed model to reference.',
    '- **Composition defaults** — orientation and size for chapter images vs. the cover (default to portrait chapter illustrations unless told otherwise), and whether space should be reserved for title text on the cover.',
    '- **Hard exclusions** — confirm the default: no text, lettering, logos, or watermarks in generated art (title text is added separately in post-production). Ask if there are other things to always avoid (e.g. graphic violence, specific real-world imagery).',
    '',
    'If the user references an existing artwork, book cover, or film for inspiration, capture the *visual qualities* they mean (brushwork, lighting, palette, composition) rather than the named source — do not write a named living artist\'s name into the style guide as an instruction to imitate their style; describe the qualities instead.',
    '',
    '### 4. Draft recurring reference blocks (optional)',
    'If the user has recurring characters, creatures, vehicles, or locations that should look consistent across images, draft one short reference block per element: name, key visual traits, distinguishing details, and how much variation is acceptable. Keep these to the visual facts needed for image generation — this is not a character profile (use `/character-setup` for narrative fields).',
    '',
    '### 5. Confirm the draft',
    'Show the assembled style guide to the user before writing it. Ask if anything is missing or wrong. Do not write the file until the user confirms.',
    '',
    '### 6. Write the file',
    'Create or update `CHAPTER_IMAGE_STYLE.md` at the book root using this structure:',
    '',
    '```markdown',
    '# Image Style Guide — [Book Title]',
    '',
    '## How to use this file',
    'Combine these blocks when generating an image:',
    '1. **Style block** — include in every prompt, always.',
    '2. **Reference blocks** — include only the ones relevant to the chosen scene.',
    '3. **Scene description** — written fresh per image.',
    '',
    '## Style block',
    '[Art style family, mood, palette, stylization level, composition defaults, hard exclusions,',
    'default size/orientation for chapter images.]',
    '',
    '## Reference blocks',
    '### [Character, creature, vehicle, or location name]',
    '[Key visual traits, distinguishing details, acceptable variation, viewing-angle rules if any.]',
    '',
    '## Cover notes',
    '[Anything specific to the book cover that differs from chapter images: composition anchor,',
    'reserved space for title text, per-language variants.]',
    '```',
    '',
    'Omit the "Reference blocks" or "Cover notes" sections if the user has nothing to put there yet — an empty section heading with no content is worse than no section.',
    '',
    '### 7. Report back',
    'Confirm the file path written, summarize the style in a sentence or two, and mention that `/chapter-image` will use this guide automatically from now on.',
    '',
    '## Rules',
    '- Do not overwrite an existing `CHAPTER_IMAGE_STYLE.md` without the user\'s confirmation.',
    '- Prefer describing visual qualities over naming a specific living artist to imitate.',
    '- Keep the guide reusable and concise — it is read on every chapter-image generation, not just once.',
    '- If `images/` already has approved artwork, the style guide must match what is already there, not contradict it.',
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
