import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/plan-beats/SKILL.md',
    version: 3,
    label:   'plan-beats skill',
    zip:     '.claude/skills/plan-beats.zip',
};

const CONTENT = [
    "---",
    "name: plan-beats",
    "description: Bindery workspace - Create or refine a beatmap for a chapter or scene. Use for /plan-beats, \"help me plan the beats\", \"let's work on the beatmap\", \"update the beatmap\", \"extend the beatmap\", \"refine chapter beats\", or \"discuss the structure of this chapter\".",
    "argument-hint: 'chapter number or scene name (optional)'",
    "---",
    "# Skill: /plan-beats",
    "",
    "Build, discuss, and refine a beatmap for a chapter or scene — from scratch, from a story idea, from the arc, or by updating an existing beatmap.",
    "",
    "**Layered writing workflow:** Beats naturally progress through detail levels as writing matures:",
    "1. **Story outline** — the chapter's role in the arc, rough shape",
    "2. **1-line beats** — one sentence per beat: subject + action + consequence",
    "3. **1-paragraph beats** — one paragraph per beat: expanded with intent, emotion, and context",
    "4. **Prose** — the written chapter",
    "",
    "This skill works at levels 1–3. When working with existing beats, detect the current level and treat advancement to the next level as a valid refinement goal.",
    "",
    "## Prerequisites",
    "This skill requires a Bindery workspace. If unsure, call `identify_book` to check. If no workspace is found, tell the user and stop.",
    "",
    "## Trigger",
    "User says `/plan-beats`, \"help me plan the beats\", \"let's work on the beatmap\", \"update the beatmap\", \"extend the beatmap\", \"refine chapter beats\", \"discuss the structure\", or any request that explicitly mentions beats, structure, or chapter planning.",
    "",
    "## Clarify first",
    "Determine the **mode** and **target** before proceeding:",
    "",
    "- **Mode** (pick one):",
    "  - **create** — build a fresh beatmap from the arc, a general idea, or a chapter outline",
    "  - **update** — add, move, remove, or reorder beats in an existing beatmap",
    "  - **refine** — improve beat descriptions, tighten pacing, or clarify purpose",
    "  - **expand** — advance beats from one detail level to the next (1-line → 1-paragraph)",
    "- **Target**: chapter number, scene name, or range (e.g. \"Chapter 5\" or \"the ambush scene in Chapter 8\")",
    "- **Detail level** (for create/expand): 1-line or 1-paragraph — infer from context or existing beats; ask only if genuinely unclear",
    "",
    "If mode is ambiguous, infer it: existing beats found and user mentions adding/removing/reordering → **update**; existing beats found and user mentions improving/tightening/clarifying → **refine**; existing 1-line beats and user mentions expanding/fleshing out → **expand**; existing beats found and intent unclear → default to **refine**; no beats found → **create**. This skill is meant to be interactive and iterative — if the user just wants a full beatmap generated without discussion, they can clarify that in the prompt or ask for a draft first.",
    "",
    "> **Project convention**: Beat storage varies by project. Common locations: `Arc/Acts/` planning files, chapter sections in `Arc/Overall.md`, inline comments in the chapter file, or a separate outline file. Detect this from the project files or workspace instructions (for example `PREFERENCES.md` or `.bindery/README.md`). If unclear, ask the user.",
    "",
    "## Tools",
    "Use these Bindery MCP tools:",
    "- `get_chapter(chapterNumber, language)` — read an existing chapter and any embedded beatmap",
    "- `get_text(path)` — read settings, `PREFERENCES.md`, `.bindery/README.md`, or memory files",
    "- `arc_list` / `arc_get` / `arc_update` — read or update structured arc files that hold beatmaps",
    "- `character_list` / `character_get` — load relevant structured character profiles",
    "- `get_notes(category, name)` — look up characters, world rules, or equipment",
    "- `search(query, language)` — find parallel moments or thematic echoes across the book",
    "",
    "> If any tool call fails or returns no data, inform the user which file could not be read and continue without it.",
    "",
    "## Steps",
    "",
    "### Phase 1 — Confirm intent",
    "1. Identify the **mode** and **target** from the user's message. Ask only if genuinely ambiguous. If the user requests a range of chapters (e.g. \"chapters 5–8\"), handle one chapter at a time and confirm before moving to the next.",
    "",
    "### Phase 2 — Load arc and settings context",
    "2. Read `.bindery/settings.json` with `get_text` (genre, target audience, story structure).",
    "3. Read `.bindery/memories/global.md`, `Arc/index.md`, `Arc/Overall.md`, and the relevant file under `Arc/Acts/` for the chapter's act. If no `Arc/` directory exists, check for alternative planning directories (e.g. `Outline/`, `Planning/`); if none found, proceed without arc context and note this to the user.",
    "",
    "### Phase 3 — Locate existing beats",
    "4. Locate beat storage using this fallback chain:",
    "   1. Check PREFERENCES.md or README for a beat storage convention.",
    "   2. If not found, check `Arc/index.md`, `Arc/Overall.md`, relevant `Arc/Acts/` files, then the chapter file itself.",
    "   3. If still not found, ask the user: *\"Where do you keep your chapter beats — in an arc file, in the chapter itself, or somewhere else?\"*",
    "   4. If no arc, outline, chapter, or beat file exists at all, tell the user there is no context to work from and ask them to describe the chapter's purpose and key events before proceeding.",
    "5. Read the relevant file(s) to extract any existing beats for the target chapter.",
    "6. If the chapter is already written, read it with `get_chapter` for scene structure and prose context.",
    "7. Read any chapter-level memory or planning note if it exists (e.g. `.bindery/memories/chXX.md`).",
    "",
    "### Phase 4 — Load focused context (as needed)",
    "8. If character-driven beats are involved: call `character_list`, then `character_get` for relevant profiles. Use `get_notes(category: \"Characters\")` only for older note layouts.",
    "9. Call `search` to check for thematic echoes or parallel beats elsewhere in the book.",
    "",
    "### Phase 5 — Discuss",
    "10. **all modes**: Align on the chapter's purpose before building beats — confirm or briefly discuss the key story beats and emotional arc. If the user has explicitly stated the chapter's purpose and key turning points, skip to Phase 6. (This is not a clarifying question about mode or target, but a contextual alignment step.)",
    "11. **update/refine**: For each existing beat, discuss whether it still serves the chapter's/scene's purpose and arc. Propose specific additions, removals, or changes — discuss before applying.",
    "",
    "### Phase 6 — Build or update the beatmap",
    "12. **create**: produce a full beatmap at the agreed detail level from the arc structure and gathered context (discussion already covered in Phase 5).",
    "13. **update**: output the updated beatmap with the additions, moves, or removals agreed in Phase 5.",
    "14. **refine**: output the refined beatmap with per-beat changes noted (improvements agreed in Phase 5).",
    "15. **expand**: output the beatmap at the next detail level — 1-line beats become 1-paragraph beats. Each paragraph should add intent, emotional context, and immediate consequence beyond what the 1-line version stated. Discuss any beats that are unclear or underdeveloped before expanding them.",
    "",
    "## Output format",
    "",
    "Match the target detail level:",
    "",
    "**1-line beats** — numbered list, one sentence per beat, concrete and action-focused:",
    "```",
    "1. [Subject + action + immediate consequence.]",
    "2. …",
    "```",
    "",
    "**1-paragraph beats** — numbered list, one short paragraph per beat. Include: what happens, why it matters to the character, and how it sets up the next beat:",
    "```",
    "1. [What happens. How the character experiences it. What it changes or makes possible.]",
    "2. …",
    "```",
    "",
    "After the beatmap, add a short **Pacing note** (2–3 sentences): where the chapter breathes, where it accelerates, and any structural gaps.",
    "",
    "For **update** or **refine** mode, also include a change summary:",
    "- `+` Added: …",
    "- `~` Changed: …",
    "- `-` Removed: …",
    "",
    "> If the user prefers a more annotated format (beat type, purpose), offer it — but don't impose it by default.",
    "",
    "## Rules",
    "- This skill is for *discussing and planning* beats — it does not write prose",
    "- Respect established world rules, character voices, and arc commitments",
    "- Keep content appropriate for the configured target audience",
    "- A standard chapter typically has 6–12 beats; short scenes may have 3–6",
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
