import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/read-in/SKILL.md',
    version: 16,
    label:   'read-in skill',
};

const CONTENT = [
    "---",
    "name: read-in",
    "description: Bindery workspace - Load project context at the start of a session — current focus, arc map, character index, memory, progress tracker, and chapter notes. Use for /read-in, \"get your bearings\", \"what were we doing\", or at the start of any working session.",
    "---",
    "# Skill: /read-in",
    "",
    "Load context and get your bearings before starting work.",
    "",
    "## Prerequisites",
    "This skill requires a Bindery workspace. If unsure, call `identify_book` to check. If no workspace is found, tell the user and stop.",
    "",
    "## Trigger",
    "User says `/read-in`, \"get your bearings\", \"what were we working on\", or at the start of a session.",
    "",
    "## Tools",
    "Use these Bindery MCP tools:",
    "- `update_workspace` — fetch and pull the workspace before loading context; also reports current branch versus the remote default branch",
    "- `memory_list` — discover which memory files exist (`global.md`, `chXX.md` files)",
    "- `session_focus_get(section?)` — read the current focus / working state from `SESSION.md`",
    "- `get_text(identifier)` — read settings and memory files",
    "- `arc_list` / `arc_get` — list and read structured arc files",
    "- `character_list` / `character_get` — list and read structured character profiles",
    "- `chapter_status_get(book)` — read the structured progress tracker",
    "- `get_overview(language)` — list all acts and chapters (only if tracker is empty or sparse)",
    "- `get_notes(category, name)` — look up key character or world notes if relevant to current focus",
    "- `search(query, language)` — find relevant passages across the book based on current focus or open questions",
    "- `get_chapter(chapterNumber, language)` — read a chapter if that's the current focus",
    "",
    "## Steps",
    "",
    "### 0. Sync repository",
    "Call `update_workspace` before loading any context.",
    "- If the update fails (for example: no remote, merge issue, or upstream problem), flag it to the user and stop — do not proceed with stale context.",
    "- If the tool reports that the current branch differs from the remote default branch, mention that briefly so the user can decide whether to switch.",
    "- If the tool reports that the workspace is already up to date, say nothing unless the branch status matters.",
    "",
    "### 1. Check for current focus",
    "Use `session_focus_get` to read the current working state from `SESSION.md` (ignore the empty-state message if it has not been created yet).",
    "",
    "### 2. Load global memory",
    "Use `get_text(\".bindery/settings.json\")` first to pick up the current book's structure and conventions.",
    "Then use `memory_list` to discover available memory files, and `get_text(\".bindery/memories/global.md\")` to load cross-chapter decisions.",
    "",
    "### 3. Read the arc and character map",
    "Use `arc_list` and `arc_get` to load the structural map (`index.md`, `Overall.md`, and any relevant act/thread/chapter arc file). Use `character_list` to load the cast map; call `character_get` only for characters relevant to the current focus.",
    "",
    "### 4. Read the progress tracker",
    "Use `chapter_status_get` to read current chapter progress. If it is empty or has fewer than 3 entries, also call `get_overview` for the full chapter listing.",
    "",
    "### 5. Determine working chapter",
    "If the current focus in `SESSION.md` names a chapter, use that.",
    "Otherwise if the tracker has a single `in-progress` chapter, use that.",
    "Otherwise — **ask the user**: \"Which chapter do you want to work on?\"",
    "",
    "### 6. Load chapter memory",
    "- Once the chapter is known (e.g. chapter 10), check `memory_list` output for a matching file (`ch10.md`). If it exists, read it with `get_text(\".bindery/memories/ch10.md\")`.",
    "- Read the full chapter text with `get_chapter` to have it fresh in context.",
    "- **Cross-check memory against chapter text:** if the chapter contradicts something in the memory file (a character name, a decision, a detail), flag it explicitly in the summary — do not silently treat memory as correct. Memory records decisions as they stood at the time; the chapter is what was actually written.",
    "",
    "### 7. Story / Arc focus",
    "Load additional context only if it is clearly relevant to the current chapter and focus:",
    "- **Characters involved in the chapter**: call `character_get` for their profiles; use `get_notes(category: \"Characters\")` only for older note layouts",
    "- **Open questions or unresolved details**: use `search` to find relevant earlier passages",
    "",
    "Do not load notes or search speculatively. If the current focus (`SESSION.md`) or the chapter memory names a specific open question, that is a good trigger; otherwise skip this step.",
    "",
    "### 8. Summarize",
    "Output a short orientation (3-6 lines):",
    "- Which chapter / scene we're in",
    "- Status from the tracker (draft / in-progress / needs-review)",
    "- Relevant arc file or open structural question",
    "- Key open decisions from global memory relevant to this chapter",
    "- Any chapter-specific notes from the chapter memory file; note if the memory file is absent or if the last entry appears old",
    "- Any memory-vs-chapter discrepancies found in Step 5",
    "- End with a phrase like: \"Ready — what would you like to work on?\"",
    "",
    "## Rules",
    "- Do not load *all* chapter memories — only the one being worked on",
    "- Keep the summary brief; this is orientation, not a full status report",
    "- Do not suggest work or ask multiple questions — one question at most (which chapter?)",
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
