import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/review/SKILL.md',
    version: 16,
    label:   'review skill',
};

const CONTENT = [
    "---",
    "name: review",
    "description: Bindery workspace - Review a chapter for language, arc consistency, and age-appropriateness. Use for /review, \"review chapter X\", \"quick review\", or \"review my changes\".",
    "---",
    "# Skill: /review",
    "",
    "Review a chapter and give structured feedback.",
    "",
    "## Prerequisites",
    "This skill requires a Bindery workspace. If unsure, call `bindery_identify_book` to check. If no workspace is found, tell the user and stop.",
    "",
    "## Trigger",
    "User says `/review`, \"review chapter X\", \"quick review\", or \"review my changes\".",
    "",
    "## Clarify first",
    "- **Scope**: recent changes (`review my changes`), a specific chapter, or overall feedback?",
    "- **Type**: **Full** (default) or **Quick** (language and typos only)? If not specified, default to Full.",
    "- If the scope includes a translated chapter file, flag it and offer `/translation-review` instead.",
    "",
    "## Tools",
    "Use these Bindery MCP tools to gather context:",
    "- `bindery_get_review_text(autoStage: true, contextLines: 3)` — returns the git diff of uncommitted changes **plus** any regions wrapped in `<!-- Bindery: Review start -->` / `<!-- Bindery: Review stop -->` markers (works even on committed work). `autoStage: true` stages reviewed files **and** removes the marker lines from disk so the next call only shows new changes. Pass more contextLines when join points to existing prose need checking",
    "- `bindery_get_chapter(chapterNumber, language)` — read the full chapter text",
    "- `bindery_get_notes(category, name)` — look up character profiles (`category: \"Characters\"`) or world rules",
    "- `bindery_search(query, language)` — find related passages across the book",
    "- `bindery_git_snapshot(message)` — after a successful review, suggest saving a snapshot",
    "",
    "## Steps",
    "",
    "### 1. Load settings and context",
    "Start by reading \".bindery/settings.json\" with `bindery_get_text(\".bindery/settings.json\")` to pick up the current book's target audience, genre, and story structure.",
    "",
    "Load the right context, pick any or all as needed:",
    "- Read `.bindery/memories/global.md`",
    "- Read `.bindery/memories/chXX.md` if it exists for chapter-specific context",
    "- Use `bindery_get_chapter` to load the chapter",
    "- For a Full review, read the relevant arc file from `Arc/`.",
    "- For \"review my changes\", use `bindery_get_review_text` to get the diff",
    "- If the diff includes translated chapter files, flag that and offer `/translation-review` for source-vs-translation feedback",
    "",
    "### 2. Perform the review",
    "",
    "**Quick** — language and typos only.",
    "",
    "**Full** — adds:",
    "- Arc consistency with the arc file",
    "- Age-appropriateness for the book's configured target audience",
    "- Character consistency (`bindery_get_notes(category: \"Characters\")`)",
    "- **Pacing** — are there sections that drag, rush, or repeat? Does the chapter breathe? Emotional beats and action beats should alternate",
    "- **Show vs tell** — is character emotion or intent over-explained rather than shown through action, dialogue, or physical detail?",
    "- **Scene purpose** — does the chapter earn its place? It should accomplish at least one of: advance the plot, reveal character, deepen the world. Flag if it does none of these",
    "- **Tone** — does the voice and register stay consistent with the surrounding chapters and the book's configured genre?",
    "",
    "### 3. Output format",
    "",
    "| Category | Location | Before | Suggested | Reason |",
    "|---|---|---|---|---|",
    "| Language | Line X | ...original... | ...suggestion... | reason |",
    "| Craft | Para 3 | — | — | Pacing: this paragraph restates what the previous one already established |",
    "",
    "- **Category** values for Full reviews: Language, Typo, Arc, Character, Pacing, Show/Tell, Scene, Tone, Age",
    "- For craft issues (Pacing, Show/Tell, Scene, Tone) the Before/Suggested columns may be empty — use the Reason column to explain the observation",
    "- Bold changed words in language suggestions",
    "- End with a 2–3 sentence overall impression",
    "",
    "### 4. After review",
    "If the review looks good, suggest: \"Want me to save a snapshot?\" (calls `bindery_git_snapshot`).",
    "",
    "## Rules",
    "- Do not rewrite unless asked — suggest only",
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
