import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/status/SKILL.md',
    version: 14,
    label:   'status skill',
    zip:     '.claude/skills/status.zip',
};

const CONTENT = [
    "---",
    "name: status",
    "description: Bindery workspace - Give a book progress snapshot — chapters done, in progress, and coming up. Use for /status, \"what's the book status\", or \"where are we\".",
    "---",
    "# Skill: /status",
    "",
    "Snapshot of the book's progress: what's done, in progress, and coming up.",
    "",
    "Primary use case: returning to a project after time away and needing to quickly understand where things stand before starting work.",
    "",
    "## Prerequisites",
    "This skill requires a Bindery workspace. If unsure, call `identify_book` to check. If no workspace is found, tell the user and stop.",
    "",
    "## Trigger",
    "User says `/status`, \"what's the book status\", or \"where are we\".",
    "",
    "## Tools",
    "Use these Bindery MCP tools:",
    "- `chapter_status_get(book)` — read the structured progress tracker from `.bindery/chapter-status.json`",
    "- `chapter_status_update(book, chapters)` — upsert chapter progress entries (send only changed chapters)",
    "- `get_overview(language)` — list all acts and chapters with titles",
    "- `session_focus_get(section?)` — read the current focus / working state from `SESSION.md`",
    "- `get_text(identifier)` — read settings.json and memory files",
    "- `arc_list` / `arc_get` — inspect arc structure and relevant arc files",
    "- `character_list` — inspect the cast index when character-profile coverage matters",
    "- `memory_list` — discover which chapter memory files exist (`chXX.md`)",
    "",
    "## Steps",
    "",
    "1. Use `get_text(\".bindery/settings.json\")` to pick up the current book's structure and conventions.",
    "2. Use `chapter_status_get` to read the current tracker. Use `memory_list` to check available memory files.",
    "3. Use `session_focus_get` to read the current focus from `SESSION.md`, and `get_text` to read `.bindery/memories/global.md` and for in-progress chapters `.bindery/memories/chXX.md`. Use `arc_list`/`arc_get` for arc context and `character_list` for cast coverage when needed.",
    "4. Use `get_overview` for the full chapter listing if the tracker is empty or incomplete.",
    "5. Check `Arc/` for what's planned vs written (`index.md`, `Overall.md`, and the relevant act/thread/chapter arc file).",
    "6. Output: overall count / done / in-progress / coming up (next 2-3 chapters) / open questions.",
    "7. If the tracker is out of date or missing entries, update it with `chapter_status_update` (upsert only the changed chapters).",
    "",
    "## Output",
    "",
    "Keep it scannable — bold headers, short lines. This is a working tool, not a narrative summary.",
    "",
    "```",
    "**[Book title]** — status as of [today's date]",
    "",
    "**Progress:** X / Y chapters complete (Act I: X/Y · Act II: X/Y · Act III: X/Y)",
    "",
    "**Done:** Ch 1, 2, 3, 4 ...",
    "**In progress:** Ch 10 — [chapter title] ([status note from tracker])",
    "**Coming up:** Ch 11, 12, 13",
    "",
    "**Arc position:** [One sentence: where in the overall story the in-progress chapter sits — e.g. \"Midpoint of Act II, approaching the second turning point.\"]",
    "",
    "**Last session:** [Date of the most recent entry in global.md or the in-progress chapter memory file, if readable. If memory files are absent or undated, say so.]",
    "",
    "**Open questions:**",
    "- [From global.md or chapter memory — unresolved decisions relevant to what comes next]",
    "",
    "**Current focus:** [From SESSION.md via session_focus_get, if present]",
    "```",
    "",
    "If the tracker was updated in Step 7, note which entries were added or changed.",
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
