import type { TemplateContext, TemplateMeta } from '../context';

export const meta: TemplateMeta = {
    file:    '.claude/skills/status/SKILL.md',
    version: 17,
    label:   'status skill',
};

const CONTENT = [
    "---",
    "name: status",
    "description: Bindery workspace - Give a book progress snapshot — chapters done, in progress, and coming up. Use for /status, \"what's the book status\", or \"where are we\".",
    "---",
    "# Skill: /status",
    "",
    "Snapshot of the book's progress: what's done, in progress, and coming up.",
    "",
    "Primary use case: returning to a project after time away and needing to quickly understand where things stand before starting work.",
    "",
    "## Prerequisites",
    "This skill requires a Bindery workspace. If unsure, call `bindery_identify_book` to check. If no workspace is found, tell the user and stop.",
    "",
    "## Trigger",
    "User says `/status`, \"what's the book status\", or \"where are we\".",
    "",
    "## Tools",
    "Use these Bindery MCP tools:",
    "- `bindery_get_overview(language)` — list all acts and chapters with titles",
    "- `bindery_session_focus_get(section?)` — read the current focus / working state from `SESSION.md`",
    "- `bindery_get_text(identifier)` — read settings.json and memory files",
    "- `bindery_arc_list` / `bindery_arc_get` — inspect arc structure and relevant arc files",
    "- `bindery_character_list` — inspect the cast index when character-profile coverage matters",
    "- `bindery_memory_list` — discover which chapter memory files exist (`chXX.md`)",
    "",
    "## Steps",
    "",
    "1. Use `bindery_get_text(\".bindery/settings.json\")` to pick up the current book's structure and conventions.",
    "2. Use `bindery_get_overview` for the full chapter listing and act structure.",
    "3. Use `bindery_memory_list` to check available memory files. Use `bindery_session_focus_get` for current focus, and `bindery_get_text` to read `.bindery/memories/global.md` plus relevant `.bindery/memories/chXX.md` files.",
    "4. Use `bindery_arc_list`/`bindery_arc_get` for arc context and `bindery_character_list` for cast coverage when needed.",
    "5. Check `Arc/` for what's planned vs written (`index.md`, `Overall.md`, and the relevant act/thread/chapter arc file).",
    "6. Output: overall chapter count / current focus / likely recently completed or active chapters / next 2-3 chapters / open questions.",
    "7. If status is ambiguous, say so explicitly and ask one clarifying question instead of guessing.",
    "",
    "## Output",
    "",
    "Keep it scannable — bold headers, short lines. This is a working tool, not a narrative summary.",
    "",
    "```",
    "**[Book title]** — status as of [today's date]",
    "",
    "**Progress:** X / Y chapters complete (Act I: X/Y · Act II: X/Y · Act III: X/Y)",
    "",
    "**Done:** Ch 1, 2, 3, 4 ...",
    "**Current focus:** Ch 10 — [chapter title] (from SESSION.md and/or recent memory)",
    "**Coming up:** Ch 11, 12, 13",
    "",
    "**Arc position:** [One sentence: where in the overall story the in-progress chapter sits — e.g. \"Midpoint of Act II, approaching the second turning point.\"]",
    "",
    "**Last session:** [Date of the most recent entry in global.md or the in-progress chapter memory file, if readable. If memory files are absent or undated, say so.]",
    "",
    "**Open questions:**",
    "- [From global.md or chapter memory — unresolved decisions relevant to what comes next]",
    "",
    "**Confidence:** [High/Medium/Low — based on recency and consistency of SESSION.md + memory signals]",
    "```",
].join('\n') + '\n';

export function render(_ctx: TemplateContext): string {
    return CONTENT;
}
